services:
  scraper:
    build: .
    container_name: scraper
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: python -m scraper.main:server

